# Generated by Django 6.0 on 2025-12-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='UserAccounts',
        ),
    ]
