# Generated by Django 5.2.3 on 2025-12-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomusers',
            name='user_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
