# Generated by Django 6.0 on 2025-12-22 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0004_remove_dmroles_is_active'),
        ('user', '0002_rename_useraccount_useraccounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounts',
            old_name='last_login',
            new_name='account_last_login',
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='account_role',
            field=models.ForeignKey(blank=True, db_column='role_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='data_model.dmroles', to_field='role_code'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='account_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
    ]
