# Generated by Django 5.2.3 on 2025-12-25 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usercustomusers_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomusers',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='user.useraccounts'),
        ),
    ]
