# Generated by Django 6.0 on 2025-12-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_last_login_useraccounts_account_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='account_role',
        ),
    ]
