# Generated by Django 5.2.3 on 2025-12-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usercustomusers_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='account_token_version',
            field=models.IntegerField(default=1),
        ),
    ]
