# Generated by Django 6.0 on 2025-12-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DmRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=50, unique=True)),
                ('role_name', models.CharField(max_length=100)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dm_roles',
            },
        ),
    ]
