# Generated by Django 5.2.3 on 2025-12-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmappname',
            name='app_type',
            field=models.IntegerField(choices=[(1, 'public'), (2, 'private'), (3, 'admin')], default=1),
        ),
    ]
