# Generated by Django 6.0 on 2025-12-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DmRole',
            new_name='DmRoles',
        ),
    ]
