# Generated by Django 5.2.3 on 2025-12-31 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0002_dmappname_app_type'),
        ('user', '0004_useraccounts_account_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmMappingAccountAppPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='account_app_pages', to='user.useraccounts', to_field='account_id')),
                ('app_code', models.ForeignKey(db_column='app_code', on_delete=django.db.models.deletion.CASCADE, related_name='account_pages', to='data_model.dmappname', to_field='app_code')),
                ('page_code', models.ForeignKey(db_column='page_code', on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='data_model.dmapppagename', to_field='page_code')),
            ],
            options={
                'db_table': 'dm_mapping_account_app_page',
                'indexes': [models.Index(fields=['account_id'], name='idx_acc_app_page_account'), models.Index(fields=['app_code'], name='idx_acc_app_page_app'), models.Index(fields=['page_code'], name='idx_acc_app_page_page')],
                'unique_together': {('account_id', 'app_code', 'page_code')},
            },
        ),
    ]
