# Generated by Django 6.0 on 2025-12-22 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0002_rename_dmrole_dmroles'),
        ('user', '0002_rename_useraccount_useraccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmAppName',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_code', models.CharField(max_length=50, unique=True)),
                ('app_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dm_app_name',
            },
        ),
        migrations.CreateModel(
            name='DmPermissions',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=255)),
                ('permission_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dm_permissions',
            },
        ),
        migrations.CreateModel(
            name='DmAppPageName',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_code', models.CharField(max_length=50, unique=True)),
                ('page_name', models.CharField(max_length=100)),
                ('app_code', models.ForeignKey(db_column='app_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmappname', to_field='app_code')),
            ],
            options={
                'db_table': 'dm_app_page_name',
            },
        ),
        migrations.CreateModel(
            name='DmMappingAccountSpecialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='user.useraccounts', to_field='account_id')),
                ('page_code', models.ForeignKey(db_column='page_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmapppagename', to_field='page_code')),
                ('permission_id', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmpermissions')),
            ],
            options={
                'db_table': 'dm_mapping_account_special_permission',
            },
        ),
        migrations.CreateModel(
            name='DmMappingAccountApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='user.useraccounts', to_field='account_id')),
                ('app_code', models.ForeignKey(db_column='app_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmappname', to_field='app_code')),
            ],
            options={
                'db_table': 'dm_mapping_account_app',
                'unique_together': {('account_id', 'app_code')},
            },
        ),
        migrations.CreateModel(
            name='DmMappingAccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='user.useraccounts', to_field='account_id')),
                ('role_code', models.ForeignKey(db_column='role_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmroles', to_field='role_code')),
            ],
            options={
                'db_table': 'dm_mapping_account_role',
                'unique_together': {('account_id', 'role_code')},
            },
        ),
        migrations.CreateModel(
            name='DmMappingRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('app_code', models.ForeignKey(db_column='app_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmappname', to_field='app_code')),
                ('page_code', models.ForeignKey(db_column='page_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmapppagename', to_field='page_code')),
                ('role_code', models.ForeignKey(db_column='role_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmroles', to_field='role_code')),
                ('permission_id', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmpermissions')),
            ],
            options={
                'db_table': 'dm_mapping_role_permission',
                'unique_together': {('role_code', 'app_code', 'page_code', 'permission_id')},
            },
        ),
    ]
