# Generated by Django 6.0 on 2025-12-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0003_dmappname_dmpermissions_dmapppagename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmroles',
            name='is_active',
        ),
    ]
