# Generated by Django 6.0 on 2025-12-22 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0004_remove_dmroles_is_active'),
        ('user', '0003_rename_last_login_useraccounts_account_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmFactory',
            fields=[
                ('factory_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('factory_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dm_factory',
            },
        ),
        migrations.CreateModel(
            name='DmBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_type', models.CharField(max_length=50)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('factory_code', models.ForeignKey(db_column='factory_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmfactory')),
            ],
            options={
                'db_table': 'dm_branch',
                'unique_together': {('factory_code', 'branch_code')},
            },
        ),
        migrations.CreateModel(
            name='DmMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('machine_name', models.CharField(max_length=100)),
                ('branch_code', models.ForeignKey(db_column='branch_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmbranch', to_field='branch_code')),
            ],
            options={
                'db_table': 'dm_machine',
                'unique_together': {('branch_code', 'machine_code')},
            },
        ),
        migrations.CreateModel(
            name='DmMachineLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=20)),
                ('line_name', models.CharField(max_length=100)),
                ('machine_code', models.ForeignKey(db_column='machine_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmmachine', to_field='machine_code')),
            ],
            options={
                'db_table': 'dm_machine_line',
                'unique_together': {('machine_code', 'line_code')},
            },
        ),
        migrations.CreateModel(
            name='DmMappingAccountBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='user.useraccounts', to_field='account_id')),
                ('branch_code', models.ForeignKey(db_column='branch_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmbranch', to_field='branch_code')),
                ('role_code', models.ForeignKey(db_column='role_code', on_delete=django.db.models.deletion.CASCADE, to='data_model.dmroles', to_field='role_code')),
            ],
            options={
                'db_table': 'dm_mapping_account_branch',
                'unique_together': {('account_id', 'branch_code', 'role_code')},
            },
        ),
    ]
